name: Test

on:
  pull_request:
    branches: "**"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go-version: [ 1.17.x ]
        os: [ ubuntu-latest, macOS-latest, windows-latest ]

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        timeout-minutes: 2
        run: |
          go build cmd/dstp/dstp.go
          go test -v -tags=integration ./...
